apiVersion: v1
kind: Service
metadata:
  name: config-service # used to be config-server
spec:
  selector:
    app: config-service
  ports:
    - port: 8081 # Port other services will use to connect
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: erodriguezln/er-config-service:latest
          ports:
            - containerPort: 8081
