apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: erodriguezln/er-employee-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_HOST
              value: 'config-service'
            - name: CONFIG_SERVER_PORT
              value: '8081'
            - name: DB_HOST
              value: 'mysql'
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: 'employeeDB'
            - name: DB_USERNAME
              value: 'root'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
