apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS attendanceDB;
    CREATE DATABASE IF NOT EXISTS employeeDB;
    CREATE DATABASE IF NOT EXISTS calculateDB;
